### ISSUE TITLE
paranoia mode: requests' proxy support

### ISSUE THREAD

**Issue by tobwen** [bundesAPI/deutschland#1]
When you're in paranoia mode and want to use (anonymous) proxies, replace this line
https://github.com/bundesAPI/deutschland/blob/b85d76551547222fd7e6f9f9e4aa4b20f3ae81de/deutschland/geo.py#L67

with this one
``` python
result = requests.get(url, headers=headers, proxies=proxies)
```

and add this to your main function (with your proxy servers of course):
``` python
proxies = {
  'http': 'http://10.10.1.10:3128',
  'https': 'http://10.10.1.10:1080',
}
```

**Comment by lukaspanni** [comment]
Would it make sense to add a configuration option to use proxies for all requests?
Could even be useful as configuration  for the whole library because _Geo_, _Bundesanzeiger_  and _Handelsregister_ all use `requests`

**Comment by LilithWittmann** [comment]
@lukaspanni sounds like a good idea. Do you wanna create a PR for that?

**Comment by lukaspanni** [comment]
> @lukaspanni sounds like a good idea. Do you wanna create a PR for that?

I'll start working on it but I don't know how long it'll take.
