### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by TrisNol** [bundesAPI/deutschland#100]
Hi @LilithWittmann @wirthual, there have been a couple of changes since the last release end of 2022. Could please create a new release of the library?

Thanks in advance

**Comment by wirthual** [comment]
Working on it. I will release 0.3.2 which will be the last release supporting 3.6 and maybe 3.7 since its EOL is in 2 weeks anyways.

**Comment by wirthual** [comment]
Tag [0.3.2 ](https://github.com/bundesAPI/deutschland/tree/0.3.2)  just got released
