### ISSUE TITLE
Python 3.11 compatability - Dependency Pillow

### ISSUE THREAD

**Issue by pdb-94** [bundesAPI/deutschland#116]
Python 3.11 supports the following Pillow verisons: Pillow >= 9.3 
[readthedocs Pillow](https://pillow.readthedocs.io/en/latest/installation.html)
deutschland 0.3.2 requires Pillow<9.0.0,>=8.3.1

Error message from prompt:
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
deutschland 0.3.2 requires Pillow<9.0.0,>=8.3.1, but you have pillow 9.3.0 which is incompatible.

**Comment by wirthual** [comment]
Hi,

thanks for reporting. Currently the minimum supported Python version is 3.6 and thus the minimum Pillow version is <9.0

Since python 3.6 and 3.7 are end of life, it totally makes sense to bump the minimum required python version to 3.8, which should allow us to also support Pillow > 9 and would fix the error as seen above.

**Comment by KoenigMax** [comment]
I would support this bump. Our security scanner flags 4 issues with Pillow 8.4.0, which are fixed in Pillow 9.0.1.

**Comment by wirthual** [comment]
Hi @KoenigMax ,
Can you have a look if these changes work for you?
https://github.com/bundesAPI/deutschland/pull/119

**Comment by KoenigMax** [comment]
Hello, I can only check this properly (as in within our corporate infrastructure), when the changes are available as a version on PyPI. Right now I can only try to install version 0.3.2 which fails because of Pillow<9.0.0.

**Comment by wirthual** [comment]
Isn't it possible for you to install a local version?

E.g. 
1.clone this repo
2.switch to the updated branch using git checkout
3. do a 'pip install /path/to/the/downloaded/repo/deutschland'

**Comment by KoenigMax** [comment]
I downloaded the zip from the project and tried a local install; still without look -- it still tried to install Pillow 8.4.0 as direct dependency of `deutschland`:

![image](https://github.com/bundesAPI/deutschland/assets/39622894/752bd487-8db9-40cf-9e97-306560a33b3e)

**Comment by KoenigMax** [comment]
Hello, thanks for the reminder. I had to resort to downloading a zip of the branch but installing that worked.

**Comment by wirthual** [comment]
Great!

You can also directly install the repo with this command:
```
pip3 install "git+https://github.com/bundesAPI/deutschland.git@feat/drop-36-37-support"
```

 Thank you for testing this out.  Looking forward to hear how it goes.

**Comment by KoenigMax** [comment]
Hello,

no I cannot, because this usage is suppressed by our network setup. I can Install by pip only from local sources or from pypi.

But as I said, the local install worked. 

Kind regards
