### ISSUE TITLE
Bundesanzeiger not working properly anymore

### ISSUE THREAD

**Issue by baniasbaabe** [bundesAPI/deutschland#125]
Running the following sample code:

```python
from deutschland.bundesanzeiger import Bundesanzeiger
ba = Bundesanzeiger()
data = ba.get_reports("Deutsche Bahn AG")
```

throws the following error:

```
[/usr/local/lib/python3.10/dist-packages/deutschland/bundesanzeiger/bundesanzeiger.py](https://localhost:8080/#) in __find_all_entries_on_page(self, page_content)
     88         soup = BeautifulSoup(page_content, "html.parser")
     89         wrapper = soup.find("div", {"class": "result_container"})
---> 90         rows = wrapper.find_all("div", {"class": "row"})
     91         for row in rows:
     92             info_element = row.find("div", {"class": "info"})

AttributeError: 'NoneType' object has no attribute 'find_all'
```

**Comment by baniasbaabe** [comment]
Nvm, Bundesanzeiger has downtime rn. But still, could a proper warning as an output be useful (if there are maintenance phases)?

**Comment by matrop** [comment]
Hey there, I'd like to tackle this issue if it's fine for you guys. Could you assign it to me?

**Comment by wirthual** [comment]
I merged your PR. Would be good to add an test case to see if the exection is thrown if the url is not availble :) E.g. test the __response method with an url which is not available.

**Comment by matrop** [comment]
Sure, I'll create a new PR for this shortly 👍

**Comment by wirthual** [comment]
Tests also merged.
