### ISSUE TITLE
Unexpected Results when requesting companies containing special characters

### ISSUE THREAD

**Issue by jopjk** [bundesAPI/deutschland#146]
When searching for companies containing special characters like &. For example when searching for "A & W Tiefbau GmbH" one gets results just for "A", because & is not URL encoded. 
A solution would be to convert company_name using urllib.parse.quote_plus(company_name)

**Comment by wirthual** [comment]
Hi,

thanks for reporting. I think this got fixed in this PR https://github.com/bundesAPI/deutschland/pull/143

We are working on a new release. Otherwise you can always build the package from source :)

**Comment by wirthual** [comment]
`0.4.2` was just released and should fix this. 

Tried it on my end:
```
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from deutschland.bundesanzeiger import Bundesanzeiger
>>> 
>>> ba = Bundesanzeiger()
>>> 
>>> data = ba.get_reports("A & W Tiefbau GmbH")

>>> 
>>> print(len(data))
20
```

Let me know if that works for you as well.

**Comment by jopjk** [comment]
Oh I didn't look in the up to date file. These changes already had been made. Now it works as expected. Thanks
