### ISSUE TITLE
Dependency Shapely: Not installed in new env

### ISSUE THREAD

**Issue by mwunderlich** [bundesAPI/deutschland#30]
The installation of Shapely doesn't work in a fresh environment. 
How to reproduce: 
- pip install deutschland

Expected result: 
- python package should be installed

What I got instead: 
- Error message:
```
 ERROR: Cannot install deutschland==0.1.0, deutschland==0.1.1, deutschland==0.1.2, deutschland==0.1.3, deutschland==0.1.4, deutschland==0.1.5, deutschland==0.1.6 and deutschland==0.1.7 because these package versions have conflicting dependencies.

The conflict is caused by:
    deutschland 0.1.7 depends on Shapely<2.0.0 and >=1.7.1
```

Workaround: 
- first install Shapely manually by running `pip install Shapely`.

My environment: 
- Mac 11.5.2. Big Sur, Python 3.9.6, pip 21.2.4

**Comment by auchtetraborat** [comment]
I have so far not been able to reproduce your issue in a fresh environment.
Shapely is listed as a dependency, as shown in pip show deutschland and on PyPI (https://pypi.org/pypi/deutschland/0.1.7/json)

```bash
$ pip install deutschland==0.1.7
$ pip show deutschland 

Name: deutschland
Version: 0.1.7
...
Location: /home/xxx/Dokumente/bundesapi/test_bundesapi/venv/lib/python3.8/site-packages
Requires: Pillow, dateparser, gql, tensorflow, boto3, Shapely, requests, slugify, beautifulsoup4, mapbox-vector-tile
Required-by:
```

My environment:
* Ubuntu 20.04, venv with 3.8.10 and pip 20.0.2
