### ISSUE TITLE
Links to Auto-Generated API-Clients documentations do not work on pypi.org

### ISSUE THREAD

**Issue by t-huyeng** [bundesAPI/deutschland#52]
The links to the API documentations for the auto-generated API-Clients are currently not working on https://pypi.org/project/deutschland/ because there are relative links.

For example: https://pypi.org/project/deutschland/docs/nina/README.md

Are absolute links the way to go here, or is there a better option?

If absolute links are okay, I can do a PR for that.

**Comment by wirthual** [comment]
Yeah I think absolute paths are better than broken paths for sure at the moment. 

In long term, the documentation needs to live at a central place. 

Thanks for the merge request
