### ISSUE TITLE
Model for CAPTCHAs in ONNX format

### ISSUE THREAD

**Issue by severinsimmler** [bundesAPI/deutschland#55]
Hi,

I have exported your model to solve the CAPTCHAs to the [ONNX format](https://en.wikipedia.org/wiki/Open_Neural_Network_Exchange). This has the advantage that you get rid of TensorFlow as a dependency (~500 MB) and can use [onnxruntime](https://onnxruntime.ai/) (~5 MB) for inference instead – would make the whole project way more lightweight. There are also significantly fewer problems updating `onnxruntime` than TensorFlow without breaking the model.

And I could also fix https://github.com/bundesAPI/deutschland/issues/8, if you're interested.

**Comment by severinsimmler** [comment]
So, if this project is still actively maintained and you're interested in adapting my suggestions, I will prepare a PR for this :blush:

**Comment by LilithWittmann** [comment]
Awesome, please create a PR!

**Comment by severinsimmler** [comment]
@LilithWittmann See https://github.com/bundesAPI/deutschland/pull/56 :)
