### ISSUE TITLE
issue with Bundesanzeiger?

### ISSUE THREAD

**Issue by ml0110** [bundesAPI/deutschland#60]
I ran the sample code, but had the following error:

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
[<ipython-input-13-d72a01062cec>](https://localhost:8080/#) in <module>()
      1 from deutschland import Bundesanzeiger
----> 2 ba = Bundesanzeiger()
      3 # search term
      4 data = ba.get_reports("Deutsche Bahn AG")
      5 # returns a dictionary with all reports found as fulltext reports

3 frames
[/usr/local/lib/python3.7/dist-packages/keras/saving/save.py](https://localhost:8080/#) in load_model(filepath, custom_objects, compile, options)
    202         if isinstance(filepath_str, str):
    203           if not tf.io.gfile.exists(filepath_str):
--> 204             raise IOError(f'No file or directory found at {filepath_str}')
    205 
    206           if tf.io.gfile.isdir(filepath_str):

OSError: No file or directory found at assets/model.h5

**Comment by wirthual** [comment]
Hi,

have a look [here](https://github.com/bundesAPI/deutschland/issues/8). This should be fixed in the newest main but that's not released yet. You could try to build the package from the source.

**Comment by wirthual** [comment]
Hey @ml0110 ,

We just did a new release. Can you give it another try?

**Comment by wirthual** [comment]
Solved in the newest release. If not, feel free to open another issue.
